library(httr)
library(xml2)
library(rvest)
library(glue)
library(future)
library(furrr)
library(quanteda)
library(quanteda.textplots)
library(quanteda.textstats)
library(plotly)
library(gganimate)
library(DT)
library(rtweet)
library(tidyverse)
library(readxl)
library(leaflet)
library(LDAvis)

# install.packages("rslp") https://github.com/dfalbel/ptstem
# install.packages("cepR")